### ISSUE TITLE
Only control one fan on Thinkpad P53

### ISSUE THREAD

**Issue by fgoodferic** [cjbdev/TPFanControl#9]
Hi,

Thanks for your update for TPFC. I use your program on my new thinkpad p53. However, it seems that the program can only control one fan(the right one) on my computer. Any suggestion for that?
Thanks @cjbdev

**Comment by BeteixZ** [comment]
I have same problem, too. Hope you can fix that. ;) @cjbdev

**Comment by stenri** [comment]
FYI, I've implemented some fix for ThinkPad P53 to turn off both fans when temperature goes below 50C:

https://github.com/stenri/TPFanControl

This is not a complete solution, but helps to keep notebook silent under no load most of the time. Meanwhile I hope Lenovo fixes ThinkPad P53 fan controlling issues.

**Comment by tigrute** [comment]
Unfortunately still experiencing the same issue with only one fan being controlled on the P53.

**Comment by stenri** [comment]
I finally found some time to research and implement a low-level fix for TPFanControl to correctly control both fans on Lenovo ThinkPad P53.

This solution works much better than previous temporary fix (there is no longer need for a weird "Mode: BIOS => Mode: Manual 1 => Mode: Manual 0" behavior, TPFanControl just sets the fans speed to whatever is configured in the .ini file):

https://github.com/stenri/TPFanControl/releases

**Comment by mattharrison** [comment]
Hi @stenri. Thanks for your work!
Do you know if this works on the P1? The @cjbdev version crashes on me.

**Comment by stenri** [comment]
@mattharrison, I did not test this on P1 or any other than P53 model. I think it should work on P52 as well as changes in my built are minimal compared to @cjbdev version. On P1 - you can try my build, it is compiled with newer Visual Studio 2019, and I made some improvement to the solution and project files. But no guarantees here.

**Comment by mattharrison** [comment]
@stenri it seemed to do a great job, very quiet! But then crashed on me...

**Comment by mattharrison** [comment]
Going to try @trevnels fork ... which also was super quiet until it crashed. How do I get debug information?

**Comment by stenri** [comment]
@mattharrison, try this debug build:

https://yadi.sk/d/Iwtqcl7VEURZag

When it crashes upload a crash dump somewhere, I can take a look at where the crash occurs.

See this link on how to enable crash dumps (I do it differently, never tried this approach, but should work):
https://helpx.adobe.com/xd/kb/how-to-generate-crash-dump-on-windows-machine.html#EnablCrashDumps

Also set DumpType == 2 (Full Dump) in the following registry key:

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps]
DumpType == 2

See here for details:
https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by EnSee** [comment]
Hi,

Am getting an error message when I attempt to install this programme.
"The code execution cannot proceed because TVicPort.dll was not found".
Have tried as administrator.
No diff

Any tips gratefully received. The fans are coming on a lot, even when idling. 

Thanks in advance

**Comment by hoegge** [comment]
This is a bug in the P53 thermal drivers. Please complain to Lenovo too as I so they fix it. 

Best

Morten H Pedersen
hoegge@gmail.com
